[package]
name = "rfib"
version = "0.1.0"
edition = "2021"

[lib]
name = "rfib"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0"
rayon = "1.9.0"

# Extra flags to make the Mac happy
[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
